"""
Django settings for fin_analysis_django project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from intuitlib.enums import Scopes
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-427n+smwlo-=_vu#qwgm2lm8(8=gmrgk+ks9ly8o&db_t&g$tq')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# For development, use localhost; for production, set DJANGO_ALLOWED_HOSTS env var
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fin_analysis_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), os.path.join(BASE_DIR, 'myapp', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fin_analysis_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'mydatabase.db',  # Ensure this is a string
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Production hosts should be set via DJANGO_ALLOWED_HOSTS env var
# Example: DJANGO_ALLOWED_HOSTS='www.relogue.com,relogue.com,sea-turtle-app-dr5wz.ondigitalocean.app'

LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = 'home'
LOGIN_REDIRECT_URL = 'home'


QB_APP_ENV = os.environ.get('QB_APP_ENV', 'sandbox')
# For production, set QB_REDIRECT_URL to your production URL
QB_REDIRECT_URL = os.environ.get('QB_REDIRECT_URL', 'http://localhost:8000/quickbooks/callback/')
#QB_REDIRECT_URL = 'http://localhost:8000'
#QUICKBOOKS_SCOPE = 'com.intuit.quickbooks.accounting'

# QuickBooks OAuth credentials - should be in environment variables for production
QUICKBOOKS_CLIENT_ID = os.environ.get('QB_CLIENT_ID', 'ABeJieEWZIujd5ZU6gigEYcnFSjSgElDrSv8tYoNIeaNB5NsA3')
QUICKBOOKS_CLIENT_SECRET = os.environ.get('QB_CLIENT_SECRET', 'Ef0QyYIrFNhZtMplSQ6hNEYRS03wRwD9ZMw4DccS')

# QuickBooks sandbox credentials - these should be stored securely in production
# For production, use environment variables and never commit tokens to source control
QUICKBOOKS_REALM_ID = os.environ.get('QUICKBOOKS_REALM_ID', '9341452098469139')
QUICKBOOKS_AUTH_CODE = os.environ.get('QUICKBOOKS_AUTH_CODE', '')
QUICKBOOKS_REFRESH_TOKEN = os.environ.get('QUICKBOOKS_REFRESH_TOKEN', '')
QUICKBOOKS_ACCESS_TOKEN = os.environ.get('QUICKBOOKS_ACCESS_TOKEN', '')

# Security settings for production
if not DEBUG:
    # HTTPS settings
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Security headers
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # HSTS settings
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Session security
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Additional security settings
SECURE_REFERRER_POLICY = 'same-origin'




