"""
Django settings for fin_analysis_django project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-427n+smwlo-=_vu#qwgm2lm8(8=gmrgk+ks9ly8o&db_t&g$tq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fin_analysis_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'myapp/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fin_analysis_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'mydatabase.db',  # Ensure this is a string
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

ALLOWED_HOSTS = ['sea-turtle-app-dr5wz.ondigitalocean.app', 'www.relogue.com', 'relogue.com', 'localhost']

LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = '/after-logout/'
LOGIN_REDIRECT_URL = 'home'


QB_APP_ENV = 'sandbox'
QB_REDIRECT_URL = 'http://localhost:8000'
QB_SCOPE = 'https://sandbox-quickbooks.api.intuit.com'

#this is for the relogue client
QUICKBOOKS_CLIENT_ID = 'ABeJieEWZIujd5ZU6gigEYcnFSjSgElDrSv8tYoNIeaNB5NsA3'
QUICKBOOKS_CLIENT_SECRET = 'Ef0QyYIrFNhZtMplSQ6hNEYRS03wRwD9ZMw4DccS'

#for GB Sandbox company, get it from the Oatuh2.0 playground
QUICKBOOKS_REALM_ID = '9341452098469139'
QUICKBOOKS_AUTH_CODE = 'AB11726690447ocCuhwn5mVUqKjs3R5AVu6PjXIoOYKRM7zVuk'
#this is the refresh token for the sandbox, expires in 101 days
QUICKBOOKS_REFRESH_TOKEN = 'AB117354165788bJ2rPPZp7CY1wRWhoQxv245BnOxOda27oiik' 
#expires in 60 mins, but then the refresh token is used to get a new one
QUICKBOOKS_ACCESS_TOKEN = 'eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiZGlyIn0..8sP0UM8dANApzt3ekpc6lA.9Du4hQRKGSKCwEw-3SiLtail8KPtJSnOy0WCSQf7PwC3zuZeF6knjiKabNMTZTT-GLEPbUy6UXe81czosJmy5V05yf9yZZ4iiGm6M4qo7BZOyBI5AiYGtvz-Od0WbiCXwLn0jrkWyQrvkZpFREnAmzkWD4F2Ux31EeDzV4NP563Hef_vUos-Y8_BjGsWvRTlO-2dHBSu4ylwUgrm6Dy7mSBH0MpYs5dCyZN7g7SwzGBjwgw4GxniTZHWsYMLceJguvNTi8wBoJsjJ1fCHWKXnQA_KKWjIdYvyyfgCQkkxz9-ODFUsIiwB9TzDC-nBbp16lAn00auotEli_JKn3m2ON6eFIfePnCf6cPW94HY1SHqJuP8MKYLZVN5A387z8SJ28XSJw58MmCnxMmyPzhNefopb3xkAIYT6H5XvCx4hX8t-nv0ORHHYWDElZFfXKmB3RastPFv-n6JHvkAlU5a2eZsNXHcJU0JOQ0WXFPk6-v48gRn4WZOuSRZlF6Xa17Mo5QfN0VZg11jpA7rsuSJUCjXTWwCVFGEy4XuMVmMHoP292E1IWR82Tv6KOfvw5VUJbUr6eI0WmwXOvAfu3Qs1DdRRkc2jgPkCiQ32DSGGK8LlCceWWv5qDT1AyhJjfeP-5UuM2JCYH2geLs6E9hTKUAvIBpYacZ0u3bxnZJBeZ50frxd1V2loRzbH3wuefIuxLTrJ1h6ior68xuVBIN1skF_aUrRWdR2y1NZkQT49UHyITUdGFfH5B8m4DPndvzN.gCfqp4nz80qtZtf7oTRs9g'




