name: fin-analysis-app
region: nyc
services:
- build_command: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    python manage.py collectstatic --noinput
  environment_slug: python
  envs:
  - key: DJANGO_SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DJANGO_DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "False"
  - key: DJANGO_ALLOWED_HOSTS
    scope: RUN_AND_BUILD_TIME
    value: "${APP_DOMAIN}"
  - key: OPENAI_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: ANTHROPIC_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: QB_CLIENT_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: QB_CLIENT_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: QB_REDIRECT_URL
    scope: RUN_AND_BUILD_TIME
    value: "https://${APP_DOMAIN}/quickbooks/callback/"
  - key: QB_APP_ENV
    scope: RUN_AND_BUILD_TIME
    value: "sandbox"
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  github:
    branch: master
    deploy_on_push: true
    repo: adakh3/fin_new
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: fin-analysis
  run_command: gunicorn --worker-tmp-dir /dev/shm fin_analysis_django.wsgi
  source_dir: /
static_sites:
- build_command: python manage.py collectstatic --noinput
  environment_slug: python
  github:
    branch: master
    deploy_on_push: true
    repo: adakh3/fin_new
  name: static
  output_dir: staticfiles
  routes:
  - path: /static
databases:
- engine: PG
  name: fin-analysis-db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"