# Generated by Django 4.2.10 on 2024-09-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='quickbooks_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
